authbase/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import UserSignupView, UserLoginView

app_name = 'authbase'

urlpatterns = [
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('quickbook.urls', namespace='quickbook')),
    path('auth/', include('authbase.urls', namespace='authbase')),
]

urlpatterns += [
    path('admin/', admin.site.urls),
]

authbase/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import UserManager
from .validator import Validator


class User(AbstractUser):
    """
        Inheriting AbstractUser Model to provide future compatibility in terms
        of adding extra fields etc
        NOTE: Kept Email as the username field.
    """
    username = None
    email = models.EmailField(
        max_length=200, unique=True, db_index=True, validators=[
            Validator.unique_email_validator])

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    # NOTE: Custom object manager, also to provide expansion
    objects = UserManager()

    def __str__(self):
        return f"User: {self.email} ID: {self.id}"

authbase/forms.py
from django import forms

from .models import User
from .validator import Validator


class UserSignupForm(forms.Form):
    first_name = forms.CharField(
        required=True,
        max_length=50,
        widget=forms.widgets.TextInput(
            attrs={
                'placeholder': 'First Name'}))
    last_name = forms.CharField(
        required=True,
        max_length=50,
        widget=forms.widgets.TextInput(
            attrs={
                'placeholder': 'Last Name'}))
    email = forms.EmailField(
        required=True,
        max_length=200,
        widget=forms.widgets.EmailInput(
            attrs={
                'placeholder': 'Email'}),
        validators=[
            Validator.unique_email_validator])
    password = forms.CharField(
        required=True,
        min_length=8,
        widget=forms.PasswordInput,
        validators=[
            Validator.password_validator])
    confirm_password = forms.CharField(
        required=True,
        min_length=8,
        widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self):
        user = User.objects.create_user(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password'],
        )
        return user


class UserLoginForm(forms.Form):
    email = forms.EmailField(
        required=True,
        max_length=200,
        widget=forms.widgets.EmailInput(
            attrs={
                'placeholder': 'Email'}))
    password = forms.CharField(
        required=True,
        min_length=8,
        widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

authbase/views.py
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView
from django.views.generic import FormView

from .forms import UserSignupForm, UserLoginForm


class UserSignupView(FormView):
    """
        User signup or register view
        @params: first_name, last_name, email, password, confirm_password
    """
    template_name = 'authbase/signup.html'
    form_class = UserSignupForm
    success_url = reverse_lazy('quickbook:bookings-list')

    def form_valid(self, form):
        user = form.save()
        # MODIFY: Instead of logging in immediately, a 2 factor auth can be added
        #         like sending and email with a code etc and serve it using VerifyUser View.
        login(self.request, user)
        return JsonResponse(
            {'success': True, 'redirect_url': str(self.success_url)})

    def form_invalid(self, form):
        errors = {
            field: [
                str(error) for error in form.errors[field]] for field in form.errors}
        return JsonResponse({'success': False, 'errors': errors})


class UserLoginView(LoginView):
    """
        User login view
        @params: email, password
    """
    template_name = 'authbase/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('quickbook:bookings-list')

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(self.request, username=email, password=password)

        if user:
            login(self.request, user)
            return JsonResponse(
                {'success': True, 'redirect_url': str(self.success_url)})
        else:
            return JsonResponse({'success': False, 'errors': 'User with email doesnt exist.'})
    
    def form_invalid(self, form):
        errors = {
            field: [
                str(error) for error in form.errors[field]] for field in form.errors}
        return JsonResponse({'success': False, 'errors': errors})

authbase/templates/authbase/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}User Signup{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'authbase/css/styles.css' %}">
</head>
<body>
    <main>
        <div class="alert alert-danger" role="alert" style="display: none;">
        </div>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

authbase/templates/authbase/login.html
{% extends 'authbase/base.html' %}
{% load static %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="card shadow-sm p-4 w-100" style="max-width: 400px;">
            <h1 class="text-center">Login</h1>
            <form class="form-group mb-3 w-100" id="login-form" method="post" action="{% url 'authbase:login' %}" novalidate>
                {% csrf_token %}
                
                {% for field in form %}
                <div class="form-field mb-3">
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div>
                        {{ field }}
                    </div>
                    <div id="error_{{ field.name }}" class="text-danger small"></div>
                </div>
                {% endfor %}
                
                <button class="btn btn-primary w-100" type="submit">Login</button>
            </form>
            <p class="mt-3 text-center small">Don't have an Account? <a href="{% url 'authbase:signup' %}" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Signup</a></p>
        </div>
    </div>
    <script src="{% static 'authbase/js/login.js' %}"></script>
{% endblock %}

authbase/templates/authbase/signup.html
{% extends 'authbase/base.html' %}
{% load static %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
        <div class="card shadow-sm p-4 w-100" style="max-width: 400px;">
            <h1 class="text-center">Signup</h1>
            <form class="form-group mb-3 w-100" id="signup-form" method="post" action="{% url 'authbase:signup' %}" novalidate>
                {% csrf_token %}
                
                {% for field in form %}
                <div class="form-field mb-3">
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div>
                        {{ field }}
                    </div>
                    <div id="error_{{ field.name }}" class="text-danger small"></div>
                </div>
                {% endfor %}
                
                <button class="btn btn-primary w-100" type="submit">Signup</button>
            </form>
            <p class="mt-3 text-center small">Already, have an Account? <a href="{% url 'authbase:login' %}" class="link-success link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Login</a></p>
        </div>
    </div>
    <script src="{% static 'authbase/js/signup.js' %}"></script>
{% endblock %}